[package]
name = "nvidia_oc"
version = "0.1.21"
edition = "2021"
license = "MIT"
description = "A simple command line tool to overclock Nvidia GPUs using the NVML library on Linux. This supports both X11 and Wayland."
repository = "https://github.com/Dreaming-Codes/nvidia_oc"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
clap_complete = "4.5.8"
nvml-wrapper = "0.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sudo2 = "0.2.1"
which = "7.0.3"
csv = "1.3"
eframe = "0.27"
